DO $$
DECLARE
  v_artist_id uuid;
  t1 uuid;
  t2 uuid;
  t3 uuid;
  t4 uuid;
  t5 uuid;
  t6 uuid;
  t7 uuid;
  t8 uuid;
  t9 uuid;
  t10 uuid;
  t11 uuid;
  t12 uuid;
  t13 uuid;
  t14 uuid;
  t15 uuid;
  s1 uuid;
  s2 uuid;
  s3 uuid;
  s4 uuid;
  s5 uuid;
  s6 uuid;
  s7 uuid;
  s8 uuid;
  s9 uuid;
  s10 uuid;
  s11 uuid;
  s12 uuid;
  s13 uuid;
  s14 uuid;
  s15 uuid;
  s16 uuid;
  s17 uuid;
  s18 uuid;
  s19 uuid;
  s20 uuid;
  s21 uuid;
  s22 uuid;
  s23 uuid;
  s24 uuid;
  s25 uuid;
  s26 uuid;
  s27 uuid;
  s28 uuid;
  s29 uuid;
  s30 uuid;
  s31 uuid;
  s32 uuid;
  s33 uuid;
  s34 uuid;
  s35 uuid;
  s36 uuid;
  s37 uuid;
  s38 uuid;
  s39 uuid;
  s40 uuid;
  s41 uuid;
  s42 uuid;
  s43 uuid;
  s44 uuid;
  s45 uuid;
  s46 uuid;
  s47 uuid;
  s48 uuid;
  s49 uuid;
  s50 uuid;
  s51 uuid;
  s52 uuid;
  s53 uuid;
  s54 uuid;
  s55 uuid;
  s56 uuid;
  s57 uuid;
  s58 uuid;
  s59 uuid;
  s60 uuid;
  s61 uuid;
  s62 uuid;
  s63 uuid;
  s64 uuid;
  s65 uuid;
  s66 uuid;
  s67 uuid;
  s68 uuid;
  s69 uuid;
  s70 uuid;
  s71 uuid;
  s72 uuid;
  s73 uuid;
  s74 uuid;
  s75 uuid;
  s76 uuid;
  s77 uuid;
  s78 uuid;
  s79 uuid;
  s80 uuid;
  s81 uuid;
  s82 uuid;
  s83 uuid;
  s84 uuid;
  s85 uuid;
  s86 uuid;
  s87 uuid;
  s88 uuid;
  s89 uuid;
  s90 uuid;
  s91 uuid;
  s92 uuid;
  s93 uuid;
  s94 uuid;
  s95 uuid;
  s96 uuid;
  s97 uuid;
  s98 uuid;
  s99 uuid;
  s100 uuid;
  s101 uuid;
  s102 uuid;
  s103 uuid;
  s104 uuid;
  s105 uuid;
  s106 uuid;
  s107 uuid;
  s108 uuid;
  s109 uuid;
  s110 uuid;
  s111 uuid;
  s112 uuid;
  s113 uuid;
BEGIN

  -- Artist
  INSERT INTO artists (name, description)
  VALUES ('ONE OK ROCK', 'Japanese rock band formed in Tokyo in 2005')
  RETURNING id INTO v_artist_id;

  -- Tours
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '20101128武道館', 2010, '武道館') RETURNING id INTO t1;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2012 残響横浜体育館', 2012, '横浜体育館') RETURNING id INTO t2;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2013 人生X君', 2013, NULL) RETURNING id INTO t3;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2014 横浜', 2014, '横浜') RETURNING id INTO t4;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2015 35XXXV', 2015, NULL) RETURNING id INTO t5;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2016 渚園', 2016, '渚園') RETURNING id INTO t6;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2017 ambition', 2017, NULL) RETURNING id INTO t7;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2018 东蛋', 2018, '东蛋') RETURNING id INTO t8;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2018 管弦', 2018, NULL) RETURNING id INTO t9;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2019 暴風眼', 2019, NULL) RETURNING id INTO t10;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2020 奇迹之旅', 2020, NULL) RETURNING id INTO t11;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2021 Day to Night', 2021, NULL) RETURNING id INTO t12;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2023 Luxury Disease', 2023, NULL) RETURNING id INTO t13;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2024 味之素', 2024, '味の素スタジアム') RETURNING id INTO t14;
  INSERT INTO tours (artist_id, name, year, location) VALUES (v_artist_id, '2025 Detox日巡', 2025, NULL) RETURNING id INTO t15;

  -- Songs
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Never Let This Go') RETURNING id INTO s1;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '夜にしか咲かない満月') RETURNING id INTO s2;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '皆無') RETURNING id INTO s3;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Shake it down') RETURNING id INTO s4;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '未完成交響曲') RETURNING id INTO s5;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'カゲロウ') RETURNING id INTO s6;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'カラス') RETURNING id INTO s7;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Living Dolls') RETURNING id INTO s8;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'アダルトスーツ') RETURNING id INTO s9;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '完全感覚Dreamer') RETURNING id INTO s10;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Wherever you are') RETURNING id INTO s11;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Yes I am') RETURNING id INTO s12;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'じぶんROCK') RETURNING id INTO s13;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Liar') RETURNING id INTO s14;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'アンサイズニア') RETURNING id INTO s15;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '恋ノアイボウ心ノクビド') RETURNING id INTO s16;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Viva Violent Fellow〜美しき') RETURNING id INTO s17;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '独り言ロンリーナ') RETURNING id INTO s18;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '内秘心書') RETURNING id INTO s19;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Nobody''s Home') RETURNING id INTO s20;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'LOST AND FOUND') RETURNING id INTO s21;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Re:make') RETURNING id INTO s22;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '世間知らずの宇宙飛行士') RETURNING id INTO s23;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Mr.現代Speaker') RETURNING id INTO s24;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'エトセトラ') RETURNING id INTO s25;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Pierce') RETURNING id INTO s26;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'C.h.a.o.s.m.y.t.h.') RETURNING id INTO s27;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Let''s take it someday') RETURNING id INTO s28;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Rock,Scissors,Paper') RETURNING id INTO s29;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'NO SCARED') RETURNING id INTO s30;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'キミシダイ列車') RETURNING id INTO s31;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Ending Story') RETURNING id INTO s32;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Deeper Deeper') RETURNING id INTO s33;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Nothing Helps') RETURNING id INTO s34;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Clock Strikes') RETURNING id INTO s35;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'All Mine') RETURNING id INTO s36;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Be the light') RETURNING id INTO s37;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'ONION!') RETURNING id INTO s38;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '69') RETURNING id INTO s39;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Juvenile') RETURNING id INTO s40;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'The Beginning') RETURNING id INTO s41;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'the same as') RETURNING id INTO s42;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Mighty Long Fall') RETURNING id INTO s43;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'A thousand miles') RETURNING id INTO s44;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '欲望に満ちた青年団') RETURNING id INTO s45;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Heartache') RETURNING id INTO s46;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Decision') RETURNING id INTO s47;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Fight the night') RETURNING id INTO s48;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Memories') RETURNING id INTO s49;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '欠落オートメーション') RETURNING id INTO s50;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Stuck in the middle') RETURNING id INTO s51;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Smiling Down') RETURNING id INTO s52;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Cry Out') RETURNING id INTO s53;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Goodbye') RETURNING id INTO s54;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Paper Planes') RETURNING id INTO s55;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Take me to the top') RETURNING id INTO s56;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Suddenly') RETURNING id INTO s57;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'One by One') RETURNING id INTO s58;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '20 years old') RETURNING id INTO s59;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Always coming back') RETURNING id INTO s60;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Taking Off') RETURNING id INTO s61;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Bombs Away') RETURNING id INTO s62;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '20/20') RETURNING id INTO s63;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Bedroom Warfare') RETURNING id INTO s64;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Listen') RETURNING id INTO s65;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Bon Voyage') RETURNING id INTO s66;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Start Again') RETURNING id INTO s67;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'I Was King') RETURNING id INTO s68;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Take what you want') RETURNING id INTO s69;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'We Are') RETURNING id INTO s70;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'One Way Ticket') RETURNING id INTO s71;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'The way back') RETURNING id INTO s72;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Last Dance') RETURNING id INTO s73;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Skyfall') RETURNING id INTO s74;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Change') RETURNING id INTO s75;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Stand Out Fit In') RETURNING id INTO s76;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Eye of the Storm') RETURNING id INTO s77;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Can''t Wait') RETURNING id INTO s78;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Head High') RETURNING id INTO s79;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Grow Old Die Young') RETURNING id INTO s80;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Worst in Me') RETURNING id INTO s81;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'In the Stars') RETURNING id INTO s82;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Push Back') RETURNING id INTO s83;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Giants') RETURNING id INTO s84;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Wasted Nights') RETURNING id INTO s85;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '完全在宅') RETURNING id INTO s86;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'The last time') RETURNING id INTO s87;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'もう一度') RETURNING id INTO s88;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Wonder') RETURNING id INTO s89;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Broken heart of gold') RETURNING id INTO s90;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'First love') RETURNING id INTO s91;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Renegades') RETURNING id INTO s92;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Save Yourself') RETURNING id INTO s93;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Let Me Let You Go') RETURNING id INTO s94;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Mad World') RETURNING id INTO s95;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Vandalize') RETURNING id INTO s96;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'So Far Gone') RETURNING id INTO s97;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Gravity') RETURNING id INTO s98;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Neon') RETURNING id INTO s99;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Your Tears are Mine') RETURNING id INTO s100;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'When They Turn the Lights On') RETURNING id INTO s101;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Delusion:All') RETURNING id INTO s102;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Make It Out Alive') RETURNING id INTO s103;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Puppets Can''t Control You') RETURNING id INTO s104;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'NASTY') RETURNING id INTO s105;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Party''s Over') RETURNING id INTO s106;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Tiny Pieces') RETURNING id INTO s107;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'This Can''t Be Us') RETURNING id INTO s108;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'C.U.R.I.O.S.I.T.Y') RETURNING id INTO s109;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Dystopia') RETURNING id INTO s110;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'Tropical Therapy') RETURNING id INTO s111;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, 'The Pilot</3') RETURNING id INTO s112;
  INSERT INTO songs (artist_id, title) VALUES (v_artist_id, '+Matter') RETURNING id INTO s113;

  -- Tour songs (order follows screenshot order)
  -- 20101128武道館
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s1, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s2, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s3, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s4, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s5, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s6, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s7, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s8, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s9, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s10, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s11, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s12, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s13, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s14, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s15, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s16, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s17, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s18, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s19, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t1, s20, 20);
  -- 2012 残響横浜体育館
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s21, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s3, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s5, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s13, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s22, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s23, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s24, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s15, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s6, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s11, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s25, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s7, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s26, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s27, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s14, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s28, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s29, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s30, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s16, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s10, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s20, 21);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t2, s31, 22);
  -- 2013 人生X君
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s32, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s33, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s34, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s7, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s15, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s27, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s28, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s5, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s13, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s35, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s11, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s36, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s14, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s37, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s38, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s39, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s40, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s22, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s10, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s41, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s20, 21);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t3, s42, 22);
  -- 2014 横浜
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s15, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s33, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s34, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s28, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s27, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s35, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s39, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s5, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s43, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s8, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s37, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s44, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s45, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s46, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s47, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s22, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s16, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s30, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s10, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s11, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s31, 21);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t4, s41, 22);
  -- 2015 35XXXV
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s48, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s41, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s49, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s50, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s33, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s51, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s35, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s52, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s14, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s53, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s54, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s46, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s55, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s56, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s57, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s10, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s43, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s15, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s58, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t5, s47, 20);
  -- 2016 渚園
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s22, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s13, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s53, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s35, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s59, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s33, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s28, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s6, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s60, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s42, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s37, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s27, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s56, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s15, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s61, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s41, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s43, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s20, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s11, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s31, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t6, s10, 21);
  -- 2017 ambition
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s62, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s38, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s33, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s61, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s63, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s53, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s35, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s64, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s39, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s60, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s11, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s65, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s66, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s67, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s68, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s69, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s41, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s43, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s70, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s71, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t7, s10, 21);
  -- 2018 东蛋
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s61, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s5, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s31, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s53, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s72, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s64, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s35, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s71, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s19, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s11, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s73, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s33, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s68, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s69, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s41, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s74, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s43, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s20, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s75, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s10, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t8, s70, 21);
  -- 2018 管弦
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s75, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s32, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s50, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s53, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s47, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s15, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s45, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s6, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s12, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s71, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s26, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s76, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s68, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s41, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s43, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s48, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s70, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t9, s10, 18);
  -- 2019 暴風眼
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s77, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s56, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s70, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s61, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s22, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s78, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s35, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s79, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s80, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s75, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s81, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s37, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s82, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s83, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s31, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s13, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s84, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s41, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s43, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s85, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s76, 21);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t10, s10, 22);
  -- 2020 奇迹之旅
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s86, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s41, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s61, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s75, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s68, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s5, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s31, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s35, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s71, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s87, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s67, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s45, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s27, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s11, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s88, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s89, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s76, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s70, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t11, s85, 19);
  -- 2021 Day to Night
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s70, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s62, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s7, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s41, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s33, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s46, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s90, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s43, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s91, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s61, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s92, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s76, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t12, s85, 13);
  -- 2023 Luxury Disease
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s89, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s93, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s15, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s94, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s35, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s6, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s95, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s96, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s97, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s46, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s98, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s99, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s33, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s92, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s100, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s41, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s31, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s42, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s70, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s85, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s101, 21);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s76, 22);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t13, s10, 23);
  -- 2024 味之素
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s102, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s50, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s22, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s13, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s93, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s47, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s92, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s89, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s31, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s103, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s11, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s69, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s7, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s99, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s41, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s70, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s43, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s76, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s28, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t14, s85, 20);
  -- 2025 Detox日巡
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s104, 1);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s93, 2);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s103, 3);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s53, 4);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s105, 5);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s8, 6);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s106, 7);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s107, 8);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s92, 9);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s36, 10);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s108, 11);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s109, 12);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s43, 13);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s41, 14);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s102, 15);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s110, 16);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s111, 17);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s112, 18);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s76, 19);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s113, 20);
  INSERT INTO tour_songs (tour_id, song_id, "order") VALUES (t15, s70, 21);

END $$;